/**
 * Extra search terms for AWS icons whose official name does not contain the
 * abbreviation people actually type ("s3", "sqs", "eks"). Keyed by the generated
 * slug of the service icon; resource icons inherit their parent service's terms.
 *
 * Only aliases the name itself does NOT already contain belong here — the search
 * box already matches the display name and the category name.
 */
export const AWS_ALIASES = {
  'amazon-simple-storage-service': ['s3', 'bucket', 'object storage'],
  'amazon-simple-storage-service-glacier': ['s3 glacier', 'archive', 'cold storage'],
  'amazon-simple-notification-service': ['sns', 'pubsub', 'topic', 'notification'],
  'amazon-simple-queue-service': ['sqs', 'queue', 'message'],
  'amazon-simple-email-service': ['ses', 'email', 'smtp'],
  'amazon-elastic-kubernetes-service': ['eks', 'k8s', 'kubernetes'],
  'amazon-elastic-container-service': ['ecs', 'containers'],
  'amazon-elastic-container-registry': ['ecr', 'registry', 'images'],
  'amazon-ec2': ['ec2', 'vm', 'instance', 'compute', 'server'],
  'amazon-relational-database-service': ['rds', 'postgres', 'mysql', 'sql'],
  'amazon-aurora': ['postgres', 'mysql', 'sql', 'database'],
  'amazon-dynamodb': ['nosql', 'key value', 'table'],
  'amazon-elasticache': ['redis', 'memcached', 'cache'],
  'amazon-memorydb': ['redis', 'cache', 'in memory'],
  'amazon-documentdb': ['mongodb', 'document', 'nosql'],
  'amazon-neptune': ['graph', 'gremlin', 'sparql'],
  'amazon-redshift': ['warehouse', 'olap', 'analytics', 'sql'],
  'amazon-athena': ['sql', 'query', 'presto', 'trino'],
  'amazon-opensearch-service': ['elasticsearch', 'search', 'logs', 'kibana'],
  'amazon-virtual-private-cloud': ['vpc', 'network', 'subnet'],
  'amazon-cloudfront': ['cdn', 'edge', 'cache'],
  'amazon-route-53': ['dns', 'domain', 'route53'],
  'amazon-api-gateway': ['apigw', 'rest', 'http', 'api'],
  'amazon-cloudwatch': ['logs', 'metrics', 'alarm', 'monitoring', 'observability'],
  'amazon-eventbridge': ['events', 'event bus', 'cloudwatch events'],
  'amazon-managed-streaming-for-apache-kafka': ['msk', 'kafka', 'streaming'],
  'amazon-kinesis': ['streaming', 'stream'],
  'amazon-elastic-file-system': ['efs', 'nfs', 'shared filesystem'],
  'amazon-elastic-block-store': ['ebs', 'volume', 'disk'],
  'amazon-cognito': ['auth', 'login', 'oauth', 'users', 'jwt'],
  'amazon-sagemaker-ai': ['ml', 'machine learning', 'training', 'notebook'],
  'amazon-bedrock': ['llm', 'genai', 'foundation model', 'ai'],
  'amazon-guardduty': ['threat detection', 'security'],
  'amazon-inspector': ['vulnerability', 'scanning', 'security'],
  'amazon-mq': ['rabbitmq', 'activemq', 'broker', 'queue'],
  'amazon-ecs-anywhere': ['ecs', 'hybrid'],
  'amazon-eks-anywhere': ['eks', 'k8s', 'hybrid'],
  'aws-lambda': ['faas', 'function', 'serverless'],
  'aws-fargate': ['serverless containers', 'ecs', 'eks'],
  'aws-step-functions': ['sfn', 'workflow', 'state machine', 'orchestration'],
  'aws-identity-and-access-management': ['iam', 'auth', 'policy', 'role', 'permissions'],
  'aws-key-management-service': ['kms', 'encryption', 'keys'],
  'aws-secrets-manager': ['secrets', 'credentials', 'vault'],
  'aws-certificate-manager': ['acm', 'tls', 'ssl', 'certificate'],
  'aws-cloudformation': ['iac', 'stack', 'template', 'infrastructure as code'],
  'aws-cloudtrail': ['audit', 'api log', 'compliance'],
  'aws-waf': ['firewall', 'web application firewall', 'security'],
  'aws-shield': ['ddos', 'protection', 'security'],
  'aws-glue': ['etl', 'catalog', 'data pipeline'],
  'aws-batch': ['jobs', 'batch processing'],
  'aws-app-runner': ['containers', 'paas'],
  'aws-amplify': ['frontend', 'hosting', 'mobile'],
  'aws-appsync': ['graphql', 'api', 'realtime'],
  'aws-direct-connect': ['dx', 'private link', 'network'],
  'aws-transit-gateway': ['tgw', 'network', 'routing'],
  'aws-privatelink': ['vpc endpoint', 'private', 'network'],
  'aws-systems-manager': ['ssm', 'parameter store', 'patching'],
  'aws-organizations': ['accounts', 'ou', 'multi account'],
  'aws-control-tower': ['landing zone', 'governance', 'multi account'],
  'aws-codebuild': ['ci', 'build', 'pipeline'],
  'aws-codepipeline': ['cd', 'pipeline', 'deployment'],
  'aws-codedeploy': ['deployment', 'release'],
  'aws-database-migration-service': ['dms', 'migration', 'replication', 'cdc'],
  'aws-data-pipeline': ['etl', 'orchestration'],
  'aws-backup': ['snapshot', 'restore', 'disaster recovery'],
  'aws-outposts-family': ['hybrid', 'on premises', 'rack'],
  'aws-storage-gateway': ['hybrid storage', 'nfs', 'smb'],
  'elastic-load-balancing': ['elb', 'alb', 'nlb', 'load balancer'],
};

/** AWS ships a few resource-icon folders under a different name than the
 * matching architecture-icon folder; fold them onto one category. */
export const AWS_CATEGORY_ALIASES = {
  iot: 'internet-of-things',
  'management-governance': 'management-tools',
};
